### ISSUE TITLE
Docker hub tags semantic versioning [question]

### ISSUE THREAD

**Issue by oleksii-andrushievich-prism** [fanout/docker-pushpin#3]
Can docker images that hosted on docker hub be tagged not only as "latest" but also with pushpin version? It would be useful for developers who prefer to use pinned versions of the software that they use in their projects.

**Comment by jkarneges** [comment]
Good idea! Version 1.24.0 is now tagged.

**Comment by oleksii-andrushievich-prism** [comment]
Thanks!

**Comment by kshpytsya** [comment]
I looks like wrong version got published:

```
# docker run --rm -it fanout/pushpin:1.24.0 pushpin --version
pushpin 1.23.0
```

**Comment by jkarneges** [comment]
Whoops, fixed.
